### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by bander454** [steve-oakey/spring-boot-sample-clientauth#1]
when i run the test i get this exception :

Caused by: java.security.cert.CertificateExpiredException: NotAfter: Tue May 30 05:10:31 AST 2017
	at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
	at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:629)
	at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:190)
	at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 65 more

**Comment by steve-oakey** [comment]
Thanks. I have updated the code (to use Spring Boot 2.x) and generated new certificates that expire in 10 years.
